services:
  block-builder:
    container_name: block-builder
    build:
      context: ${PWD}/repos/block-builder
      dockerfile: ${PWD}/Dockerfile.block-builder
    image: block-builder
    command: /app/jwt.hex http://execution-layer
    ports:
      - "8561:8561"
    environment:
      - RUST_LOG=debug
    networks:
      - igra-network
    volumes:
      - ${PWD}/jwt.hex:/app/jwt.hex
    depends_on:
      - execution-layer

  execution-layer:
    container_name: execution-layer
    image: ghcr.io/paradigmxyz/reth
    entrypoint: /root/reth/run-igra-dev-el.sh
    ports:
      - "9001:9001"
    environment:
      - RUST_LOG=info,sync::stages=trace,downloaders=trace,debug
    networks:
      - igra-network
    volumes:
      - ./jwt.hex:/root/reth/jwt.hex
      - ./repos/execution-layer/genesis.json:/root/reth/genesis.json
      - ./repos/execution-layer/run-igra-dev-el.sh:/root/reth/run-igra-dev-el.sh

  rpc-provider:
    container_name: rpc-provider
    build:
      context: ${PWD}/repos/igra-rpc-provider
      dockerfile: ${PWD}/Dockerfile.rpc-provider
    image: rpc-provider
    environment:
      - RUST_LOG=debug
      - KASWALLET_PASSWORD=''
    networks:
      - igra-network
    depends_on:
      - kaswallet
    ports:
      - "8545:8535"

  kaswallet:
    container_name: kaswallet
    build:
      context: ${PWD}/repos/kaswallet
      dockerfile: ${PWD}/Dockerfile.kaswallet
    image: kaswallet
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - RUST_LOG=debug
    networks:
      - igra-network
    volumes:
      - ${PWD}/keys.json:/app/keys.json
    command: ["--devnet", "--logs-level=debug", "--keys-file", "/app/keys.json", "--server", "ws://host.docker.internal:17610", "--listen", "0.0.0.0:8082"]
    ports:
      - "8082:8082"

  viaduct:
    container_name: viaduct
    build:
      context: ${PWD}/repos/rusty-kaspa-private
      dockerfile: ${PWD}/Dockerfile.viaduct
    image: viaduct
    environment:
      - RUST_LOG=debug
      - REPLAY_ON_ERROR=-1
      - SYNC_THREADS=64
    volumes:
      - viaduct_data:/app/storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - igra-network
    command: ["--ip-port=host.docker.internal:17610", "--bb-ip-port=block-builder:8561"]
    depends_on:
      - block-builder

networks:
  igra-network:

volumes:
  viaduct_data: