events {
    worker_connections 1024;  # Maximum number of simultaneous connections
}

http {
  upstream l2rpc1 {
    server rpc-provider:8535;
  }

  upstream l1_explorer {
    server kaspa_explorer:8080;
  }

  upstream l1_Explorer_ws {
    server simply_kaspa_socket_server:8000;
  }

  # List of valid access tokens
  map $uri $valid_token {
    default "invalid"; # Default if token is not found
    ~^/9fb27a48631c486b9e5937ac140829d6/ valid;
    ~^/ad32094f78934ba484bd16c97e20f056/ valid;
    ~^/e9c4658047e74271b58f203648ac1b3f/ valid;
    ~^/f73ad68c74924aa9b3e9a12058cf294f/ valid;
    ~^/17abe38d29cf4037b7045ea621c97f50/ valid;
    ~^/49df2873ab7946598e0f1ac65b02d14e/ valid;
    ~^/a2e19f37d58648c9b71c3a5f902d140e/ valid;
    ~^/c4201b9fea7a4a5f801d2394876e39b4/ valid;
    ~^/2b8d3945f0174ac8ae9c470d2856e90c/ valid;
    ~^/85740ace9d164ba59e0c1f39d72b16a3/ valid;
    ~^/fb8d7c877f0ff3f032143f9dbcc3840a/ valid;
    ~^/5510d7cfbfc5eb986e0575a3b0496d53/ valid;
    ~^/fd07318d4a567c187c893a1db9d2f94a/ valid;
    ~^/1e75a963ab938d39aeed7c51db0be2e6/ valid;
    ~^/b7c0d14d862d9fa4444ff9e44c731b90/ valid;
    ~^/25f22c6c1bcadcd80ae1838528dddb8d/ valid;
    ~^/61e697e1b3f6d2330a84fb875a4d16eb/ valid;
    ~^/efc258967210a3b231244390dd233186/ valid;
    ~^/ed528d1a44c0271cba4dba394682a945/ valid;
    ~^/82d586ce355f11b190e28bb499bbd9e9/ valid;
    ~^/d1ed97440f59cc1a4030b2c760182e7f/ valid;
    ~^/4c7c4e51effa50dff827047f20b0bee5/ valid;
    ~^/c24b3d68bb96f85adf5aebfdd6a409be/ valid;
    ~^/fdeb9c0eff14aba9f4c7312d693d0f34/ valid;
    ~^/82f14b862054bcbd45b9018f6b2b14cc/ valid;
    ~^/fafda38366d687aba4b52a62a08b36d8/ valid;
  }

  # RPC-Provider
  server {
    listen 8545;

    # Deny requests with an invalid token
    if ($valid_token = "invalid") {
      return 403; # Forbidden, invalid token
    }
    # Rewrite URI to remove the token part
    rewrite ^/[^/]+(/.*)$ $1 break;

    location / {
      proxy_pass http://l2rpc1;
    }
 }

  # KASPA-Explorer
  server {
    listen 8000;

    location / {
      proxy_pass http://l1_explorer;
    }
  }

  server {
    listen 8001;

    location / {
      proxy_pass http://l1_Explorer_ws;

      # WebSocket specific settings
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;

      # Optional but recommended settings
      proxy_read_timeout 86400;    # 24h, prevents timeout for long-lived connections
      proxy_send_timeout 86400;    # 24h
      proxy_buffering off;         # Recommended for WebSocket connections
    }
  }
}
